server:
  port: 8200

spring:
  application:
    name: pethotel
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: false
    hibernate:
      use-new-id-generator-mappings: false
  datasource:
    url: jdbc:mysql://localhost:3306/pet_hotel?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
    hikari:
      maximum-pool-size: 10
  jackson:
    serialization:
      fail-on-empty-beans: false

datasource:
    url: jdbc:mysql://localhost:3306/pet_hotel?useUnicode=true&characterEncoding=UTF-8


flyway:
  locations: classpath:db/migration
  encoding: UTF-8
